_target_: diffusion_policy.workspace.train_diffusion_transformer_hybrid_workspace_custom.TrainDiffusionTransformerHybridWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_action_mse_error={test_action_mse_error:.3f}.ckpt
    k: 5
    mode: min
    monitor_key: test_action_mse_error
dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 10
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2024.08.10-1_train_diffusion_transformer_hybrid_grasp
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_diffusion_transformer_hybrid
  - lift_image
  - default
multi_run:
  run_dir: data/outputs/2024.08.10/1_train_diffusion_transformer_hybrid_grasp
  wandb_name_base: 2024.08.10-1_train_diffusion_transformer_hybrid_grasp
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_transformer_hybrid
obs_as_global_cond: true
optimizer:
  betas:
  - 0.9
  - 0.95
  learning_rate: 0.0001
  obs_encoder_weight_decay: 1.0e-06
  transformer_weight_decay: 0.001
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_transformer_hybrid_image_policy.DiffusionTransformerHybridImagePolicy
  causal_attn: true
  crop_shape:
  - 216
  - 288
  eval_fixed_crop: true
  horizon: 10
  n_action_steps: 8
  n_cond_layers: 0
  n_emb: 256
  n_head: 4
  n_layer: 8
  n_obs_steps: 2
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  obs_as_cond: true
  obs_encoder_group_norm: true
  p_drop_attn: 0.3
  p_drop_emb: 0.0
  shape_meta:
    action:
      shape:
      - 9
    obs:
      camera_1_image:
        shape:
        - 3
        - 240
        - 320
        type: rgb
      eef_pos:
        shape:
        - 3
      eef_quat:
        shape:
        - 4
      camera_2_image:
        shape:
        - 3
        - 240
        - 320
        type: rgb
shape_meta:
  action:
    shape:
    - 9
  obs:
    camera_1_image:
      shape:
      - 3
      - 240
      - 320
      type: rgb
    eef_pos:
      shape:
      - 3
    eef_quat:
      shape:
      - 4
    camera_2_image:
      shape:
      - 3
      - 240
      - 320
      type: rgb
task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
    abs_action: true
    dataset_path: data/grasp_dataset_12.hdf5
    horizon: 10
    n_obs_steps: 2
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    shape_meta:
      action:
        shape:
        - 9
      obs:
        camera_1_image:
          shape:
          - 3
          - 240
          - 320
          type: rgb
        eef_pos:
          shape:
          - 3
        eef_quat:
          shape:
          - 4
        camera_2_image:
          shape:
          - 3
          - 240
          - 320
          type: rgb
    use_cache: true
    val_ratio: 0.02
  dataset_path: data/grasp_dataset_12.hdf5
  dataset_type: ph
  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
    abs_action: true
    crf: 22
    dataset_path: data/grasp_dataset_12.hdf5
    fps: 10
    max_steps: 100
    n_action_steps: 8
    n_envs: 1
    n_obs_steps: 2
    n_test: 1
    n_test_vis: 1
    n_train: 1
    n_train_vis: 1
    past_action: false
    render_obs_key: camera_1_image
    shape_meta:
      action:
        shape:
        - 9
      obs:
        camera_1_image:
          shape:
          - 3
          - 240
          - 320
          type: rgb
        eef_pos:
          shape:
          - 3
        eef_quat:
          shape:
          - 4
        camera_2_image:
          shape:
          - 3
          - 240
          - 320
          type: rgb
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    train_start_idx: 0
  name: lift_image
  shape_meta:
    action:
      shape:
      - 9
    obs:
      camera_1_image:
        shape:
        - 3
        - 240
        - 320
        type: rgb
      eef_pos:
        shape:
        - 3
      eef_quat:
        shape:
        - 4
      camera_2_image:
        shape:
        - 3
        - 240
        - 320
        type: rgb
  task_name: lift
task_name: lift_image
training:
  checkpoint_every: 5
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 1000
  max_train_steps: null
  max_val_steps: null
  num_epochs: 200
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 50
val_dataloader:
  batch_size: 64
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: false
